FROM python:3.12

WORKDIR /app

COPY ../requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ../migrations ./migrations
COPY ../alembic.ini .
COPY ../.env .
COPY ../server ./server
COPY ../config.py ./server

CMD alembic upgrade head & python3 server/main.py